# Generated by Django 4.2.13 on 2024-06-19 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='category',
            field=models.CharField(default='Uncategorized', max_length=50),
        ),
    ]
